### PR TITLE
[AZTH] Now Hodir enter in combat state.

### PR DESCRIPTION
**Pull request by Ercules76**

### CODE REVIEW

**Comment by Yehonal** [comment]
Great work[around?] , did you test it?

**Comment by Ercules76** [comment]
Yes i tested on my local and the boss enter in combat, i haven't test all phase fight.

**Comment by Yehonal** [comment]
@Ercules76 Nice, we'll test it on devbox and test-server soon, i'm merging it now :) thanks

**Comment by FrancescoBorzi** [comment]
:+1:

**Pull request merged**
